### ISSUE TITLE
add additional disks encryption

### ISSUE THREAD

**Issue by alegrey91** [89luca89/terrible#19]
When we define additional disks, could be useful to have an `encryption` variable to ask Ansible to encrypt the disk.
The variable should be `optional`, and needs also other related variables like `password`, or `password_file` from we can retrieve the password to encrypt the disk.
The inventory could become as follow:
```yaml
...
    data_disks:
        disk-storage:
        size: 100
        pool: default
        format: xfs
        mount_point: /mnt/data_storage
        encryption: True
            password: password123
```
