### ISSUE TITLE
Assertion too strict on terraform target hypervisor

### ISSUE THREAD

**Issue by 89luca89** [89luca89/terrible#29]
```yaml
# Verifiy the correctness of the parameters.
- name: Validate 'terraform_target_hypervisor' parameter
  assert:
    quiet: yes
    that:
      - hostvars['terraform_node']['terraform_target_hypervisor'] | ipaddr
    fail_msg: >
      You are trying to use an unsupported terraform_target_hypervisor value.
  when:
    - hostvars['terraform_node']['terraform_target_hypervisor'] is defined
```

@alegrey91 this is too strict, an hostname should be a valid value
