### ISSUE TITLE
Problems with multi-hypervisors setup

### ISSUE THREAD

**Issue by 89luca89** [89luca89/terrible#31]
Right now the use of groups and `terraform_node` variables to handle multiple hypervisors does not work well, because of: https://github.com/ansible/ansible/issues/32247 

This issue suggests to use unique groups for-each parent groups (ex: hypervisor_1, hypervisor_2 etc etc)

while goind this route is feasible, I think it will break compatibility with existing roles that want a specific group structure, 

I think we should find a solution that is generic and does not impose specific group names/structures to work.

**Comment by 89luca89** [comment]
```yaml
all:
  hosts:
    terraform_node:
      ansible_host: localhost
      ansible_connection: local
    hypervisor_1:
      terraform_target_hypervisor: thinkpad-w540.lan
      terraform_target_hypervisor_user: root
      terraform_target_hypervisor_port: 22
      terraform_target_hypervisor_password: password
    hypervisor_2:
      terraform_target_hypervisor: 10.90.20.12
      terraform_target_hypervisor_user: root
      terraform_target_hypervisor_port: 22
      terraform_target_hypervisor_password: password
  children:
    deploy:
      vars:
        disk_source: "/var/lib/libvirt/images/_Centos-8-template.qcow2"
        os_family: RedHat
        pool_name: default
        ssh_password: root
        ssh_port: 22
        ssh_user: root
        ssh_public_key_file: '~/.ssh/id_rsa.pub'
        set_new_password: password123
      children:
        master_nodes:
          hosts:
            master-node-0:
              os_family: FreeBSD
              disk_source: "/var/lib/libvirt/images/_freebsd-terraform.qcow2"
              cpu: 2
              memory: 1024
              ansible_host: 192.168.122.200
              hypervisor: hypervisor_1
              network_interfaces:
                if-0:
                  name: default
                  ip: 192.168.122.200
                  gw: 192.168.122.1
                  mac_address: "AA:BB:CC:11:24:67"
                  type: nat
                  dns:
                    - 192.168.122.1
                if-1:
                  name: enp0s25
                  ip: 192.168.100.200
                  gw: 192.168.100.1
                  mac_address: "AA:BB:CC:11:25:67"
                  type: macvtap
                  default_route: True
                  dns:
                    - 192.168.100.1
        slave_nodes:
          hosts:
            slave-node-0:
              os_family: Debian
              disk_source: "/var/lib/libvirt/images/_debian10-terraform.qcow2"
              cpu: 1
              memory: 512
              hypervisor: hypervisor_2
              ansible_host: 192.168.122.201
              network_interfaces:
                if-0:
                  name: default
                  ip: 192.168.122.201
                  gw: 192.168.122.1
                  mac_address: "AA:BB:CC:11:24:68"
                  type: nat
                  dns:
                    - 192.168.122.1
                if-1:
                  name: enp0s25
                  ip: 192.168.100.201
                  gw: 192.168.100.1
                  type: macvtap
                  default_route: True
                  dns:
                    - 192.168.100.1
                if-2:
                  name: enp0s25
                  ip: 192.168.100.211
                  gw: 192.168.100.1
                  type: macvtap
                  dns:
                    - 192.168.100.1

```


This is a first approach of the idea, shift all the VMs in the group `deploy` (that will be used as `hosts` in main.yml), specify hypervisors and terraform_nodes as **hosts** outside of this group.

Link each VM to his own hypervisor, and let the setup_vars.yml task set the various inferences based on this.

main.yml:

```yaml
- hosts: deploy
  gather_facts: False
  max_fail_percentage: 0
  roles:
    - terraform

```
