### ISSUE TITLE
Cloud Init Support

### ISSUE THREAD

**Issue by 89luca89** [89luca89/terrible#50]
Adding cloudinit support for images can be really useful for the disk_source selection.

the terraform-libvirt provider, supports cloudinit images by using a specific resource:

```terraform
data "template_file" "user_data" {
  template = file("./cloud_init.yml")
}

resource "libvirt_cloudinit_disk" "commoninit" {
  name      = "commoninit.iso"
  user_data = data.template_file.user_data.rendered
}

```

we should add them in the `terraform-vm.tf.j2` file inside an if/else checking if this is a cloud-init image

the `cloud_init.yml` file can be a template, this is an example of user data:

```yaml
#cloud-config
ssh_pwauth: True
chpasswd:
  list: |
    root:password
  expire: False

```

this enables the root user via ssh with password, so terrible can use it as a normal image
