### ISSUE TITLE
[IMPROVEMENT] Add autostart option for VMs

### ISSUE THREAD

**Issue by 89luca89** [89luca89/terrible#55]
We should add an `autostart` variable that sets the VM autostart to true or false.
If not specified, default to false.

example:

```yaml
            cloud-init-node-0:
              os_family: RedHat
              #disk_source: "~/Desktop/cloudinit/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2"
              disk_source: "https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2"
              cpu: 1
              memory: 512
              hypervisor: hypervisor_1
              ansible_host: 192.168.122.200
              cloud_init: True
              autostart: True
              network_interfaces:
                if-0:
                  ...
              data_disks:
                disk-1:
                 ...
                disk-swap:
                 ...
```
