### ISSUE TITLE
[IMPROVEMENT] Support for other providers

### ISSUE THREAD

**Issue by 89luca89** [89luca89/terrible#88]
We should support other providers like:

- oVirt using: https://github.com/oVirt/terraform-provider-ovirt
- Proxmox using: https://github.com/Telmate/terraform-provider-proxmox

To include multiple providers we should think on how we want to specify the provider, for example:

```yaml
    hypervisor_1:
      ansible_host: remote_kvm_machine.foo.bar
      ansible_user: root
      provider_type: Proxmox
```

Or something similar, also we should think on how the code generation will behave, for example

```
roles/terrible/templates/Libvirt
└── ......tf.j2
roles/terrible/templates/Proxmox
└── ......tf.j2
roles/terrible/templates/oVirt
└── ......tf.j2
```

And use the `provider_type` as a variable to discover the templates.

Discussion open on how to approach the problem
